# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi_menu(self, Menu):
        Menu.setObjectName("Menu")
        Menu.setWindowModality(QtCore.Qt.NonModal)
        Menu.resize(934, 703)
        self.verticalFrame = QtWidgets.QFrame(Menu)
        self.verticalFrame.setGeometry(QtCore.QRect(140, 160, 631, 252))
        self.verticalFrame.setFocusPolicy(QtCore.Qt.NoFocus)
        self.verticalFrame.setAcceptDrops(False)
        self.verticalFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.verticalFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.verticalFrame.setLineWidth(1)
        self.verticalFrame.setMidLineWidth(0)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setContentsMargins(50, 50, 50, 50)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalFrame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalFrame)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.verticalFrame)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.verticalFrame)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_warnings = QtWidgets.QLabel(self.verticalFrame)
        self.label_warnings.setObjectName("label_warnings")
        self.verticalLayout.addWidget(self.label_warnings)
        self.label_4 = QtWidgets.QLabel(self.verticalFrame)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_table_print = QtWidgets.QPushButton(self.verticalFrame)
        self.pushButton_table_print.setObjectName("pushButton_table_print")
        self.horizontalLayout_3.addWidget(self.pushButton_table_print)
        self.pushButton_table_search = QtWidgets.QPushButton(self.verticalFrame)
        self.pushButton_table_search.setObjectName("pushButton_table_search")
        self.horizontalLayout_3.addWidget(self.pushButton_table_search)
        self.pushButton_convertation = QtWidgets.QPushButton(self.verticalFrame)
        self.pushButton_convertation.setObjectName("pushButton_convertation")
        self.horizontalLayout_3.addWidget(self.pushButton_convertation)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Dialog"))
        self.label.setText(_translate("Menu",
                                      "<html><head/><body><p><span style=\" font-size:16pt;\">"
                                      "Выберите файл:</span></p></body></html>"))
        self.pushButton.setText(_translate("Menu", "Открыть"))
        self.pushButton_table_print.setText(_translate("Menu", "Вывод таблицы"))
        self.pushButton_table_search.setText(_translate("Menu", "Поиск по параметрам"))
        self.pushButton_convertation.setText(_translate("Menu", "Конвертировать файл"))
