# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convert.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Conv(object):
    def setupUi(self, Conv):
        Conv.setObjectName("Conv")
        Conv.resize(820, 635)
        self.verticalLayoutWidget = QtWidgets.QWidget(Conv)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 10, 671, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_header = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_header.setObjectName("label_header")
        self.verticalLayout.addWidget(self.label_header)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setInputMask("")
        self.lineEdit.setFrame(True)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.pushButton_convert = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_convert.setObjectName("pushButton_convert")
        self.horizontalLayout.addWidget(self.pushButton_convert)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_warning = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_warning.setText("")
        self.label_warning.setObjectName("label_warning")
        self.horizontalLayout_2.addWidget(self.label_warning)
        self.pushButton_ch_table = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_ch_table.setObjectName("pushButton_ch_table")
        self.horizontalLayout_2.addWidget(self.pushButton_ch_table)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Conv)
        self.comboBox_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Conv)

    def retranslateUi(self, Conv):
        _translate = QtCore.QCoreApplication.translate
        Conv.setWindowTitle(_translate("Conv", "Dialog"))
        self.label_header.setText(_translate("Conv", "<html><head/><body><p align=\"center\">"
                                                     "<span style=\" font-size:16pt;\">"
                                                     "Конвертация файлов</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Conv", ".sqlite"))
        self.comboBox.setItemText(1, _translate("Conv", ".db"))
        self.comboBox.setItemText(2, _translate("Conv", ".csv"))
        self.pushButton_convert.setText(_translate("Conv", "->"))
        self.comboBox_2.setItemText(0, _translate("Conv", ".sqlite"))
        self.comboBox_2.setItemText(1, _translate("Conv", ".db"))
        self.comboBox_2.setItemText(2, _translate("Conv", ".csv"))
        self.pushButton_ch_table.setText(_translate("Conv", "Выбрать таблицу"))
